-- ══════════════════════════════════════════════════════════════════════════════
-- TradingBots.fun — Migration 004: invite-only access + leaderboard + campaigns
--
-- Overview:
--   Signups are invite-only.  Every invite code belongs to a campaign.
--   Campaigns run weekly and award prizes for top % return.
--   The leaderboard_snapshots table captures a weekly equity snapshot per tenant
--   so % return is comparable across accounts of any size (including $20).
--
-- Design choices:
--   • Invite codes are short (8 chars), uppercase, human-typeable.
--   • max_uses = 1 for personal referral codes, higher for campaign blast codes.
--   • Leaderboard ranks on pct_return (equity / start_equity - 1) so a $20
--     account that doubles beats a $10k account that gains 1%.
--   • campaign_prizes stores what was awarded — useful for tax/compliance.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid(), encode()

-- ── 1. Campaigns ──────────────────────────────────────────────────────────────
-- One row per weekly contest.  The operator inserts rows here to launch a new
-- campaign.  The leaderboard page reads the active campaign.

CREATE TABLE IF NOT EXISTS campaigns (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    slug            TEXT        UNIQUE NOT NULL,  -- url-safe name, e.g. "week-12-2026"
    title           TEXT        NOT NULL,         -- "Week 12 · $200 Prize Pool"
    description     TEXT,                         -- shown on leaderboard page
    starts_at       TIMESTAMPTZ NOT NULL,
    ends_at         TIMESTAMPTZ NOT NULL,
    prize_pool_usd  NUMERIC(10,2) NOT NULL DEFAULT 0,
    prizes          JSONB,       -- [{"rank":1,"usd":100},{"rank":2,"usd":60},...]
    is_active       BOOLEAN     NOT NULL DEFAULT FALSE,  -- only one active at a time
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_campaigns_active  ON campaigns (is_active, ends_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaigns_slug    ON campaigns (slug);

COMMENT ON TABLE campaigns IS
    'Weekly contest campaigns with prize pools; one row per contest period';

-- ── 2. Invite codes ───────────────────────────────────────────────────────────
-- Gates all signups.  Generated by the operator or by existing users (referral).

CREATE TABLE IF NOT EXISTS invite_codes (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    code            TEXT        UNIQUE NOT NULL,  -- "TB-ABCD1234" — shown to users
    campaign_id     UUID        REFERENCES campaigns (id) ON DELETE SET NULL,
    created_by      UUID        REFERENCES tenants (id) ON DELETE SET NULL,
    -- NULL created_by = operator-generated blast code
    -- Non-NULL = personal referral code issued to an existing user
    max_uses        SMALLINT    NOT NULL DEFAULT 1,
    uses_count      SMALLINT    NOT NULL DEFAULT 0,
    expires_at      TIMESTAMPTZ,
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    note            TEXT        -- operator memo (e.g. "Twitter launch blast")
);

CREATE INDEX IF NOT EXISTS idx_invite_code       ON invite_codes (code) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_invite_creator    ON invite_codes (created_by) WHERE created_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invite_campaign   ON invite_codes (campaign_id);

COMMENT ON TABLE invite_codes IS
    'Invite codes gate all signups; personal referral codes issued to existing users';

-- ── 3. Invite code attribution on tenants ────────────────────────────────────

ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS invite_code_used  TEXT,   -- the code they entered at signup
    ADD COLUMN IF NOT EXISTS invited_by        UUID REFERENCES tenants (id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS campaign_id       UUID REFERENCES campaigns (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tenants_invited_by ON tenants (invited_by) WHERE invited_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tenants_campaign   ON tenants (campaign_id) WHERE campaign_id IS NOT NULL;

COMMENT ON COLUMN tenants.invite_code_used IS 'The invite code entered at signup — for audit and referral attribution';
COMMENT ON COLUMN tenants.invited_by       IS 'The tenant who generated the invite code (personal referrals)';
COMMENT ON COLUMN tenants.campaign_id      IS 'Campaign this user signed up under — determines which leaderboard they compete on';

-- ── 4. Leaderboard snapshots ──────────────────────────────────────────────────
-- Written once per day per tenant (by a nightly cron / maintenance task).
-- Stores equity at the START of each campaign week so % return is anchored.
-- Also stores the end-of-period snapshot for ranking.
--
-- Strategy: snapshot equity at campaign start when tenant first appears in
-- that campaign.  Daily snapshots let us reconstruct the equity curve for the
-- leaderboard sparklines.

CREATE TABLE IF NOT EXISTS leaderboard_snapshots (
    id              BIGSERIAL   PRIMARY KEY,
    tenant_id       UUID        NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    campaign_id     UUID        NOT NULL REFERENCES campaigns (id) ON DELETE CASCADE,
    snapshot_date   DATE        NOT NULL DEFAULT CURRENT_DATE,
    equity_usd      NUMERIC(18,8) NOT NULL,
    -- Anchor equity: first equity recorded for this tenant in this campaign.
    -- Stored redundantly here for fast % return calc without a subquery.
    start_equity_usd NUMERIC(18,8) NOT NULL,
    pct_return      NUMERIC(10,4) GENERATED ALWAYS AS (
        CASE WHEN start_equity_usd > 0
             THEN ((equity_usd - start_equity_usd) / start_equity_usd) * 100
             ELSE 0
        END
    ) STORED,
    -- Total trades placed during this campaign period (for tiebreaking and
    -- filtering bots with zero activity).
    trades_in_period INTEGER NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, campaign_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_lb_campaign_rank
    ON leaderboard_snapshots (campaign_id, pct_return DESC, snapshot_date DESC);

CREATE INDEX IF NOT EXISTS idx_lb_tenant
    ON leaderboard_snapshots (tenant_id, campaign_id, snapshot_date DESC);

COMMENT ON TABLE leaderboard_snapshots IS
    'Daily per-tenant equity snapshots per campaign; pct_return is computed column for ranking';

-- ── 5. Campaign prizes awarded ────────────────────────────────────────────────
-- Append-only record of every prize payment.  Used for compliance/tax.

CREATE TABLE IF NOT EXISTS campaign_prizes (
    id              BIGSERIAL   PRIMARY KEY,
    campaign_id     UUID        NOT NULL REFERENCES campaigns (id),
    tenant_id       UUID        NOT NULL REFERENCES tenants (id),
    rank            SMALLINT    NOT NULL,
    prize_usd       NUMERIC(10,2) NOT NULL,
    pct_return      NUMERIC(10,4) NOT NULL,  -- their final % return
    awarded_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    payment_method  TEXT,        -- "USDC_transfer" | "stripe_credit" | "manual"
    payment_ref     TEXT,        -- txn hash or Stripe transfer ID
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_prizes_campaign ON campaign_prizes (campaign_id);
CREATE INDEX IF NOT EXISTS idx_prizes_tenant   ON campaign_prizes (tenant_id);

COMMENT ON TABLE campaign_prizes IS
    'Immutable prize payment ledger for each campaign; used for tax / compliance reporting';

-- ── 6. Live leaderboard view ──────────────────────────────────────────────────
-- Returns the current standings for the active campaign.
-- Shows latest snapshot per tenant (MAX snapshot_date for the campaign).

CREATE OR REPLACE VIEW leaderboard_live AS
WITH latest AS (
    SELECT DISTINCT ON (ls.tenant_id)
        ls.tenant_id,
        ls.campaign_id,
        ls.equity_usd,
        ls.start_equity_usd,
        ls.pct_return,
        ls.trades_in_period,
        ls.snapshot_date
    FROM leaderboard_snapshots ls
    JOIN campaigns c ON c.id = ls.campaign_id AND c.is_active = TRUE
    ORDER BY ls.tenant_id, ls.snapshot_date DESC
)
SELECT
    row_number() OVER (ORDER BY l.pct_return DESC, l.trades_in_period DESC) AS rank,
    t.display_name,
    t.wallet_address,
    l.equity_usd,
    l.start_equity_usd,
    l.pct_return,
    l.trades_in_period,
    l.snapshot_date,
    l.campaign_id,
    l.tenant_id
FROM latest l
JOIN tenants t ON t.id = l.tenant_id
WHERE l.trades_in_period > 0   -- exclude zero-activity accounts from ranking
ORDER BY rank;

COMMENT ON VIEW leaderboard_live IS
    'Current standings for the active campaign; rank by pct_return (levels $20 vs $10k accounts)';

-- ── 7. Weekly campaign summary view ──────────────────────────────────────────

CREATE OR REPLACE VIEW campaign_summary AS
SELECT
    c.id,
    c.slug,
    c.title,
    c.starts_at,
    c.ends_at,
    c.prize_pool_usd,
    c.is_active,
    count(DISTINCT t.id)                       AS signups,
    count(DISTINCT ls.tenant_id)               AS active_traders,
    round(avg(ls.pct_return), 2)               AS avg_pct_return,
    round(max(ls.pct_return), 2)               AS top_pct_return,
    sum(ls.trades_in_period)                   AS total_trades,
    count(DISTINCT ic.id)                      AS invite_codes_issued,
    sum(ic.uses_count)                         AS invite_codes_used
FROM campaigns c
LEFT JOIN tenants t          ON t.campaign_id = c.id
LEFT JOIN leaderboard_snapshots ls
    ON ls.campaign_id = c.id
    AND ls.snapshot_date = (
        SELECT MAX(ls2.snapshot_date) FROM leaderboard_snapshots ls2
        WHERE ls2.campaign_id = c.id AND ls2.tenant_id = ls.tenant_id
    )
LEFT JOIN invite_codes ic    ON ic.campaign_id = c.id
GROUP BY c.id
ORDER BY c.starts_at DESC;

COMMENT ON VIEW campaign_summary IS
    'Per-campaign stats for admin dashboard: signups, active traders, avg return, codes issued/used';

-- ── 8. Seed: first campaign and operator blast codes ─────────────────────────
-- Operator must replace these UUIDs / codes before going live.
-- This seeds a "Launch Week" campaign and 50 invite codes.

INSERT INTO campaigns (slug, title, description, starts_at, ends_at, prize_pool_usd, prizes, is_active)
VALUES (
    'launch-week-1',
    'Launch Week · $200 Prize Pool',
    'The top 3 traders by % return this week split $200. Any deposit size — even $20 — can win. Two bots running, one week, best % return takes the pot.',
    date_trunc('week', now()),
    date_trunc('week', now()) + INTERVAL '7 days',
    200.00,
    '[{"rank":1,"label":"🥇 1st place","usd":100},{"rank":2,"label":"🥈 2nd place","usd":60},{"rank":3,"label":"🥉 3rd place","usd":40}]'::jsonb,
    TRUE
) ON CONFLICT (slug) DO NOTHING;

-- ── Helper function: generate a random invite code ───────────────────────────
-- Called by the Rust layer via SELECT generate_invite_code(); returns "TB-XXXXXXXX"

CREATE OR REPLACE FUNCTION generate_invite_code() RETURNS TEXT
LANGUAGE sql AS $$
    SELECT 'TB-' || upper(substring(encode(gen_random_bytes(5), 'hex') FROM 1 FOR 8));
$$;

-- ── Helper function: claim an invite code ────────────────────────────────────
-- Atomically increments uses_count and returns the invite_code row if valid.
-- Returns NULL if code not found, inactive, expired, or at max uses.

CREATE OR REPLACE FUNCTION claim_invite_code(p_code TEXT)
RETURNS TABLE (
    invite_id   UUID,
    campaign_id UUID,
    created_by  UUID
) LANGUAGE plpgsql AS $$
DECLARE
    v_id        UUID;
    v_campaign  UUID;
    v_creator   UUID;
BEGIN
    UPDATE invite_codes
    SET    uses_count = uses_count + 1
    WHERE  code       = upper(p_code)
      AND  is_active  = TRUE
      AND  (expires_at IS NULL OR expires_at > now())
      AND  uses_count < max_uses
    RETURNING id, campaign_id, created_by
    INTO v_id, v_campaign, v_creator;

    IF v_id IS NULL THEN
        RETURN;   -- empty result set = invalid / exhausted code
    END IF;

    RETURN QUERY SELECT v_id, v_campaign, v_creator;
END;
$$;

COMMENT ON FUNCTION claim_invite_code IS
    'Atomically validates and claims one use of an invite code; returns empty if invalid/exhausted';
